app:
  jwt:
    secret-key: QPRpaCkex7e4OnstMhNHqA==
    response-object-identifier: "data"
    expiration-time: 8

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
  spring:
    h2:
      console:
        enabled: true
        path: /h2-console